[sprite]
name = "Tiley McTile Face"
pixels = """
2223003223003222
2223300330033222
2231133113311322
2231131111311322
2223313113133222
2231111331111322
2311111331111132
2331113333111332
2313331111333132
2311311111131132
2311311111131132
2231131111311322
2223313333133222
2222344444432222
2222234444322222
2222223333222222
"""

[colors]
[colors.0]
red = 11
green = 161
blue = 0

[colors.1]
red = 255
green = 0
blue = 0

[colors.2]
red = 255
green = 0
blue = 255

[colors.3]
red = 0
green = 0
blue = 0

[colors.4]
red = 255
green = 3
blue = 0

